parameters:
    env(EYEPIN_API_URL): 'https://apiv3.eyepin.com/interface3.php'
    inspiredminds.contao_eyepin_gateway.api_url: '%env(EYEPIN_API_URL)%'

services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoEyepinGateway\:
        resource: ../src/

    InspiredMinds\EyepinApi\EyepinApiFactory:
        arguments:
            - '%inspiredminds.contao_eyepin_gateway.api_url%'
